spring:
  application:
    name: engine-notification-service

  profiles:
    active: feature-toggle

  kafka:
    producer:
      bootstrap-servers: localhost:9092

eureka:
  client:
    # ????? ??????? ????? ??????? ?????????? ?????? ????????? ?? ??????
    initial-instance-info-replication-interval-seconds: 0
    fetch-registry: true
    should-enforce-registration-at-init: false
    filter-only-up-instances: true
    instance-info-replication-interval-seconds: 2
  instance:
    instance-id: ${random.uuid}
    # ????? ????? ????? ??????? ?????? ????????? ???????
    lease-expiration-duration-in-seconds: 5
    # ???????? ???????? heartbeat ?????????
    lease-renewal-interval-in-seconds: 1

server:
  port: 0

propagation:
  filters:
    trace-id:
      enabled: true
      order: 0
    logging:
      enabled: true
      order: 1

logging:
  level:
    org:
      springframework:
        cloud: debug

